'bootstrap' => [
    ...
    'access',
],
...
'modules' => [
    ...
    'access' => ['class' => 'app\modules\access\Module'],
],
...
'controllerMap' => [
    'migrate' => [
        ...
        'migrationPath' => [
            ...
            '@app/modules/access/migrations',
        ],
    ],
],
...