'bootstrap' => [
    ...
    'access',
],
...
'modules' => [
    ...
    'access' => ['class' => 'Smoren\Yii2\AccessManager\Module'],
],
...
'controllerMap' => [
    'migrate' => [
        ...
        'migrationPath' => [
            ...
            '@app/vendor/smoren/yii2-module-access-manager/src/migrations',
        ],
    ],
],
...